# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    php_errors:
        log: true

    assets:
        enabled: false

    router:
        enabled: false

    session:
        enabled: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
