services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $domain: '%env(string:DOMAIN)%'
            $tailscaleKey: '%env(string:TAILSCALE_KEY)%'
            $tailscaleUser: '%env(string:TAILSCALE_USER)%'
            $tailscaleNet: '%env(string:TAILSCALE_NET)%'
            $cloudflareKey: '%env(string:CLOUDFLARE_KEY)%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
